workos/workos-php

- .semaphore/semaphore.yml
- composer.json
- lib/Client.php
- lib/Exception/GenericException.php
- lib/RequestClient/CurlRequestClient.php
- lib/SSO.php
- lib/Version.php
- lib/WorkOS.php
- tests/TestHelper.php
- tests/WorkOS/ClientTest.php
- tests/WorkOS/SSOTest.php
[Asana](https://app.asana.com/0/1171029126931209/1170059789104319/f)
This PR adds Draft Connection support to the SDK. Also some QOL and testing enhancements.
> Draft Connection Support + Enhancements

- README.md
- lib/Client.php
- lib/DirectorySync.php
- lib/RequestClient/CurlRequestClient.php
- lib/Resource/BaseWorkOSResource.php
- lib/Resource/Directory.php
- lib/Resource/DirectoryGroup.php
- lib/Resource/DirectoryUser.php
- lib/Resource/Profile.php
- lib/SSO.php
- lib/Util/Request.php
- tests/TestHelper.php
- tests/WorkOS/AuditTrailTest.php
- tests/WorkOS/ClientTest.php
- tests/WorkOS/DirectorySyncTest.php
- tests/WorkOS/SSOTest.php
[Asana](https://app.asana.com/0/1171846862894397/1172201455775218/f)
Directory Sync support. This PR is sorta big.. but here's some highlights:
- DIRECTORY SYNC
- Bunch of resources added to represent the records being pulled from WorkOS
> Directory Sync Support

- lib/Version.php
All caught up in terms of feature set. Let's get this thing published. This PR bumps the version in preparation for that.
> Bump Version

- lib/Version.php
Bump one more time per suggestion [here](https://github.com/workos-inc/workos-php/pull/6#pullrequestreview-400594165).
> Bump to version to 0.3.0

- README.md
- lib/AuditTrail.php
- lib/DirectorySync.php
- lib/Resource/BaseWorkOSResource.php
- lib/Resource/Event.php
- lib/Resource/EventAction.php
- lib/Version.php
- tests/WorkOS/AuditTrailTest.php
- Support for Audit Trail get Endpoint
- Event and EventAction resources
- Bump version to 0.4.0
> Audit Trail GET \events endpoint support

- lib/Resource/Profile.php
- lib/Version.php
- tests/WorkOS/SSOTest.php
* On the API, we recently exposed raw_attributes, the original profile
response we receive from the IdP. This update passes this data through
the SDK.
* Updates the SDK to 0.5.0
> Expose raw_attributes on WorkOS\Resource\Profile

- README.md
- lib/Portal.php
- lib/Resource/Organization.php
- tests/WorkOS/PortalTest.php
* Returns a list of the organizations accessible to the provided
API key. Includes pagination functionality via the before and after
properties.
> Add \WorkOS\Portal and the listOrganizations() function

- README.md
- lib/Portal.php
- tests/WorkOS/PortalTest.php
* Adds the ability to create an organization via the SDK for use
with the Admin Portal.
> Add createOrganization() to \WorkOS\Portal

- lib/Portal.php
- lib/Resource/PortalLink.php
- tests/WorkOS/PortalTest.php
* Adds an SDK method to generate an Admin Portal link.
> Add generateLink() to \WorkOS\Portal

- README.md
- lib/Resource/Directory.php
- lib/Resource/EventAction.php
- lib/SSO.php
- lib/Version.php
- lib/WorkOS.php
- tests/TestHelper.php
- tests/WorkOS/AuditTrailTest.php
- tests/WorkOS/ClientTest.php
- tests/WorkOS/DirectorySyncTest.php
- tests/WorkOS/PasswordlessTest.php
- tests/WorkOS/SSOTest.php
- Remove project ID and add environment ID to EventAction and Directory resources
- Deprecate project ID in favor of client ID
- Retire promoteDraftConnections
- Bump version to 0.9.0
> Buncha smol things

- lib/SSO.php
- tests/WorkOS/SSOTest.php
- Adds functionality to retrieve a list of Connections using the WorkOS SSO REST API
> Add `GET /connections`

- lib/DirectorySync.php
- tests/WorkOS/DirectorySyncTest.php
PR to add a Directory Deletion function for the DSync file and a unit test for the function.
> Add Delete Directory function to Dsync files

- composer.json
PR to add illuminate/support to ^5.0 || ^6.0 || ^7.0 || ^8.0" to the composer.json file based on a customer request
> added illuminate/support package to the composer file

- README.md
https://linear.app/workos/issue/SDK-89/audit-readmes-in-sdks
> Update README for consistency across SDKs

- lib/DirectorySync.php
- lib/RequestClient/CurlRequestClient.php
PR to create an HTTP Method to delete and support the deleteDirectory and deleteConnection functions that were already authored.
> Add Delete HTTP request method

- lib/Client.php
- lib/Portal.php
- lib/RequestClient/CurlRequestClient.php
PR to create a HTTP PUT Method and create an update organization function that uses the PUT method.
> Add HTTP PUT method and update organization function

- lib/Version.php
PR to bump version for inclusion of a new HTTP Put method and the update organization function supported by PUT method.
> Update Version to 0.9.6 for Update Org function

- lib/Organizations.php
PR to add a getOrganization function to the SDK
> create getOrganization function

- lib/Passwordless.php
- tests/WorkOS/PasswordlessTest.php
PR to Add connection param support for create passwordless session and update the unit test to accept connection as well.
> Add connection param support for create passwordless session

- lib/Organizations.php
PR to add deleteOrganization function.
> Add delete organization function

- .semaphore/semaphore.yml
- lib/SSO.php
- tests/WorkOS/SSOTest.php
PR to create getprofile function
> Create getProfile function

- lib/Passwordless.php
- tests/WorkOS/PasswordlessTest.php
Also updated unit test for this argument.
> adding expires_in argument to the createSession function

- lib/Resource/Webhook.php
- lib/Webhook.php
- tests/WorkOS/WebhookTest.php
Adds new class/resource for webhook in order to create a public function that users can leverage to input a webhook's header and body and receive a validated webhook object. 
Resolves SDK-238
> Add webhook validation methods

- lib/DirectorySync.php
- tests/WorkOS/DirectorySyncTest.php
> Add getDirectory function (gets directory by ID) and unit test

- lib/Version.php
Update lib/version to 1.5.0 for a version bump.
> Bump to 1.5.0

- composer.json
- lib/SSO.php
Add optional flag to both connection and domain parameters for SSO getAuthorizationURL so domain can be removed from the example app.
> Add optional flag to connection and domain params

- lib/Version.php
Update version to 1.6.1 for new release
> Update version to 1.6.1

- lib/Version.php
Update version to 1.6.0 for release
> Feature/update version 1.6.0

- lib/Version.php
> Bump Version to 1.7.0

- lib/MFA.php
- lib/Resource/AuthenticationChallengeSms.php
- lib/Resource/AuthenticationChallengeTotp.php
Need to break authentication challenge resource into two separate resources for SMS and TOTP so that SMS can be formatted WITH expires_at and TOTP can be formatted WITHOUT expires_at.
> Split Authentication Challenge into SMS and TOTP

- lib/SSO.php
> Include `organization_id` in listConnections

- tests/WorkOS/OrganizationsTest.php
Update authorization header for organizations idempotency-key test
> Update authorization header for organizations idempotency-key test

- lib/Version.php
> Update version to 1.15.0

- lib/MFA.php
- tests/WorkOS/MFATest.php
Add getFactor and deleteFactor methods to MFA class
> Add getFactor and deleteFactor methods to MFA class

- lib/Version.php
- Add success_url to generateLink (#125)
- Add getFactor and deleteFactor methods to MFA class (#122)
> Bump version to v1.18.0

- lib/Portal.php
- tests/WorkOS/PortalTest.php
> Add `log_streams` Admin Portal intent

- lib/Version.php
> Major Version Bump to 3.0.0

- lib/Version.php
Version bump to deploy https://github.com/workos/workos-php/pull/140
```
[ ] Yes
```
> Bump Version to 3.1.1

- lib/Version.php
> Bump Version to 3.2.0

- lib/Version.php
> Bump Version to v3.3.0

- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
Adds the deleteUser and updateUserPassword Functions
```
[ ] Yes
```
> Add deleteUser and updateUserPassword funcs

- composer.json
- tests/TestHelper.php
- tests/WorkOS/AuditLogsTest.php
- tests/WorkOS/ClientTest.php
- tests/WorkOS/DirectorySyncTest.php
- tests/WorkOS/MFATest.php
- tests/WorkOS/SSOTest.php
Bump phpUnit version
```
[ ] Yes
```
> Bump phpUnit version

- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
User Management - Delete User : use new api path
```
[ ] Yes
```
> User Management - Delete User : use new api path

- composer.json
- tests/WorkOS/AuditLogsTest.php
- tests/WorkOS/ClientTest.php
- tests/WorkOS/DirectorySyncTest.php
- tests/WorkOS/MFATest.php
- tests/WorkOS/SSOTest.php
> Revert "Bump phpUnit version"

- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
User Management - new Email verification api
```
[ ] Yes
```
> User Management - new Email verification api

- lib/UserManagement.php
Reshuffle function in user management. Group them by feature category.
```
[ ] Yes
```
> User Management - Order functions

- lib/Resource/OrganizationMembership.php
- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
User Management - add new organization membership apis
```
[ ] Yes
```
> User Management - add new organization membership apis

- lib/Resource/Invitation.php
- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
User Management - Add Invitation apis
```
[ ] Yes
```
> User Management - Add Invitation apis

- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
User Management - Delete update password function
```
[ ] Yes
```
> User Management - Delete update password function

- lib/Resource/UserWithOrganizationIdResponse.php
- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
Authentication methods for user management
```
[ ] Yes
```
> Authentication methods for user management

- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
User Management - Add AuthenticateWithEmailVerification function
```
[ ] Yes
```
> User Management - Add AuthenticateWithEmailVerification function

- lib/Version.php
> WorkOS - PHP SDK 4.1.0

- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
> Add screen hint to getAuthorizationUrl

- lib/Version.php
> Bump version number to 4.7.0

- lib/UserManagement.php
- tests/WorkOS/UserManagementTest.php
Adds log out URL method.
```
[ ] Yes
```
> Add logout url method

- lib/Version.php
Bump version to 4.8.0.
```
[ ] Yes
```
> Bump version to 4.8.0

- lib/Version.php
This version includes:
- https://github.com/workos/workos-php/pull/238
```
[ ] Yes
```
> Bump to version 4.12.0

- lib/Resource/Profile.php
- lib/Resource/RoleResponse.php
- lib/SSO.php
- tests/WorkOS/SSOTest.php
Adds `role` property to SSO profile.
```
[X] Yes
```
[Docs PR](https://github.com/workos/workos/pull/31441)
> Add role to profile

- lib/Version.php
Version bump to release #246 
```
[ ] Yes
```
> Minor version bump 4.14.0

- lib/Version.php
Bump to version 4.15.0.
```
[ ] Yes
```
> Bump to version 4.15.0

- lib/Version.php
Bump to version 4.17.0.
```
[ ] Yes
```
> Bump to version 4.17.0

- lib/Organizations.php
And fix typo in getOrganization docstring
```
[ ] Yes
```
> Add function to get organization by external id

- lib/Version.php
Bump to version 4.22.0.
```
[ ] Yes
```
> Bump to version 4.22.0

- lib/Resource/Profile.php
- tests/WorkOS/SSOTest.php
Add customAttributes field to SSO Profile.
```
[ ] Yes
```
> Add customAttributes field to SSO Profile

- lib/Version.php
Bump to version 4.23.0.
```
[ ] Yes
```
> Bump to version 4.23.0
