README.md, lib/Resource/Connection.php, lib/Resource/Domain.php, lib/SSO.php, lib/Version.php, tests/WorkOS/SSOTest.php
- Add new SSO method to use new connections endpoint for creating a connection from a draft connection token
- Deprecate promoteDraftConnection
=> Hook up with new connections endpoint

lib/Resource/Profile.php, lib/Version.php, tests/WorkOS/SSOTest.php
* Passes the `connection_id` Profile object attribute through to the SDK. We currently expose `connection_id` via the `/sso/token` API endpoint.
* Updates the SDK version to `0.7.0`.
=> Expose `connection_id` on Profile Objects

lib/Version.php
Forgot to bump the version identifier in the last release
=> Update version identifier to 0.8.x

lib/SSO.php, tests/WorkOS/SSOTest.php
- Adds functionality to retrieve a single Connection using the WorkOS SSO REST API
=> Add `GET /connections/:id`

lib/Resource/Directory.php, tests/WorkOS/DirectorySyncTest.php
- Removes `bearer_token` attribute from Directory resource
=> Remove Unneeded Attribute from `Directory` Interface

lib/SSO.php
- Adds support for an `OrganizationId` parameter to the `listConnections` function. Allows for retrieving a list of all Connections associated with the given `OrganizationId`.
=> Add `OrganizationId` Parameter to `listConnections`

lib/Client.php, lib/SSO.php, tests/WorkOS/SSOTest.php
- Adds functionality to delete a single Connection using the WorkOS SSO REST API
=> Add `DELETE /connections/:id`

lib/Util/Request.php
The file Util/Request.php has a typo:
namespace WorkOs\Util <-------- should be WorkOS\Util
submitting PR to fix this
=> Fixed WorkOs typo changed to WorkOS

lib/Version.php
Bumping version from 0.9.4 to 0.9.5 for the new HTTP Delete method for supporting deleting connections and deleting directories
=> Version bump for HTTP Delete method

lib/RequestClient/CurlRequestClient.php
PR to fix a bug reported by customer - the count function is intended to be used with arrays and was causing a critical error for them, however it was just a warn in my initial application. Either way, I resolved the issue with the warning/error no longer occurring.
=> Fixed bug reported by customer in DELETE Method

lib/SSO.php, lib/WorkOS.php, tests/TestHelper.php
This PR removes support for the deprecated `projectID` parameter.
This is a breaking change that will be part of `v1.0.0`.
Resolves SDK-165.
=> Remove support for deprecated `projectID` parameter

lib/Resource/BaseWorkOSResource.php, lib/Resource/ProfileAndToken.php, lib/SSO.php, tests/WorkOS/SSOTest.php
This PR renames the `getProfile` method to `getProfileAndToken`.
This is a breaking change that will be part of `v1.0.0`.
Resolves SDK-158.
=> Rename `getProfile` to `getProfileAndToken`

lib/Organizations.php, lib/Portal.php, tests/WorkOS/OrganizationsTest.php, tests/WorkOS/PortalTest.php
This PR moves the Organization operations to their own top-level class in the SDK.
This is a breaking change that will be part of `v1.0.0`.
Resolves SDK-171.
=> Move Organization operations to the top-level

lib/SSO.php, tests/WorkOS/SSOTest.php
This PR removes the deprecated `createConnection` method from the SDK.
This is a breaking change that will be part of `v1.0.0`.
Resolves SDK-179.
=> Remove `createConnection` method

.semaphore/semaphore.yml
PHPbrew no longer supports version 5.6.40, so the unit test returns an error on every execution:
Exception: Version 5.6.40 not found.
Trace:
0) PhpBrew\Command\InstallCommand->execute('5.6.40')
1) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['5.6.40'])
2) CLIFramework\CommandBase->executeWrapper(['5.6.40'])
3) CLIFramework\Application->run(['/opt/homebrew/bin/phpbrew', '--no-progress', 'install', '5.6.40'])
4) PhpBrew\Console->runWithTry(['/opt/homebrew/bin/phpbrew', '--no-progress', 'install', '5.6.40'])
5) require('phar:///opt/homebrew/Cellar/phpbrew/1.27.0/bin/phpbrew/bin/phpbrew')
This is fine as version 5.6.40 was end of lifed back in January.
=> Drop version 5.6.40 from semaphore test

lib/Resource/DirectoryUser.php, tests/WorkOS/DirectorySyncTest.php
There was no linear task to add idp_id for the PHP SDK, however I saw it in the API documentation so decided to also add this in while exposing groups.
=> expose idp_id and groups for directory users

lib/Resource/ProfileAndToken.php, tests/WorkOS/SSOTest.php
getProfileAndToken is returning a payload that includes raw in the profile object which
is denormalizing the payload between OAuth payloads and SAML payloads. It looked like we were running $response[profile] through the constructFromResponse function twice so I reduced this to once and that resolved the issue in testing
=> Fix GetProfileandToken returning 'raw' in payload 

.semaphore/semaphore.yml
This PR fixes an issue where we were trying to use PHP 7.2 prior to installing it in CI.
=> Install PHP 7.2 before trying to use it

lib/Organizations.php, lib/Resource/Organization.php, tests/WorkOS/OrganizationsTest.php
This PR adds support for the `allowProfilesOutsideOrganization` field for organization objects and operations.
Resolves SDK-261.
=> Add support for `allowProfilesOutsideOrganization` for organizations

lib/Version.php
Bumping to 1.4.0 to push a release including webhook validation and GET directory/:id function.
=> Bump to 1.4.0

.gitignore, lib/Client.php, lib/SSO.php, tests/WorkOS/SSOTest.php
Resolves SDK-382.
We should consider refactoring this method to consume a class/object for the parameters and then publishing a major version. Having this many arguments is no bueno.
We could also leverage the builder pattern here which is sometimes used in PHP.
=> Add support for domain_hint and login_hint parameters

lib/SSO.php, tests/WorkOS/SSOTest.php
Add organization parameter to GetAuthorizationURL function and include a notice message in the function for users who are strictly calling via domain and not any other parameter to identify the connection.
=> Add organization parameter to GetAuthorizationURL

lib/Webhook.php
Customer reported that a name with special characters (á, ó) are breaking the validateWebhook function. This PR will remove a line of code that calls utf8_decode which appears to be causing the issue.
=> Remove utf-8 decode line 

lib/Version.php
1.5.1 fixes a bug in the Webhook::constructEvent function that was causing non utf8 characters to return an error.
=> Bump to 1.5.1

lib/Resource/Directory.php, tests/WorkOS/DirectorySyncTest.php
isDirectories() throws an error as it's expecting environment_id to be passed as a value but it's no longer included within the response payload.  This causes an Undefined error for Array types when trying to reference the environment_id to write it to $instance->values
Where it's breaking:
https://github.com/workos-inc/workos-php/blob/2f2a44643dadd6159f864ddbbccf08a3e2301dfa/lib/Resource/BaseWorkOSResource.php#L35-L38
Where it needs to be fixed
https://github.com/workos-inc/workos-php/blob/2f2a44643dadd6159f864ddbbccf08a3e2301dfa/lib/Resource/Directory.php#L23-L31
Request where this code changed occurred
https://github.com/workos-inc/workos/pull/7422
=> Remove environment_id from SDK

lib/Resource/AuthenticationChallengeTotp.php, tests/WorkOS/SSOTest.php
Currently expires_at only indexed in SMS challenge responses. Adding to totp challenge responses to avoid a 'notice' being presented when the field is returned. Also adding unit test logic for PR https://github.com/workos/workos-php/pull/97
=> Expose `expires_at` in totp challenge responses

lib/Webhook.php, tests/WorkOS/WebhookTest.php
In addition to the previous public method in the Webhooks class, constructEvent, we also uncover the private methods in this class:
verifyHeader
getTimestamp
getSignature
Followed Ruby PR as an example: https://github.com/workos/workos-ruby/pull/171
=> Uncover private methods in webhooks class

lib/Exception/BaseRequestException.php, tests/WorkOS/ClientTest.php
Fixes https://github.com/workos/workos-php/issues/108
Encountering an error in the API generates: 
`'Undefined index: message' from /var/www/api/v1/vendor/workos/workos-php/lib/Exception/BaseRequestException.php:33`
This could be a notice, warn, or error depending on PHP version and framework. 
Additionally the error returned is not informative:
`Uncaught WorkOS\Exception\BadRequestException in /Users/svaughn/Documents/php-example-applications/php-sso-example/vendor/workos/workos-php/lib/Client.php:77`
**This is because of the previous line of code:**
`$this->message = $responseJson["message"];`
**tries to reference a 'message' field on the API response, which does not exist (possibly did at some point?).** 
This PR will remove the undefined index, and return a more informative error …
=> Display error and error_description in error handling

lib/SSO.php
Resolves https://github.com/workos/workos-php/issues/124 by removing default NULL value from domain on getAuthorizationUrl function based on suggestion https://php.watch/versions/8.0/deprecate-required-param-after-optional
=> Remove default null on domain in getAuthorizationUrl

lib/Resource/BaseWorkOSResource.php, lib/Resource/ProfileAndToken.php, tests/WorkOS/SSOTest.php
Currently the Profile returned in ProfileAndToken is not getting mapped to any resource, forcing users to operate on the values with snake_case instead of camelCase which differs from our other API responses. This will map the profile to the Profile Resource, and still allow the raw unmapped values to be returned as well.
=> Map Profile from ProfileAndToken to Profile Resource

lib/Version.php
A major release version bump for https://github.com/workos/workos-php/commit/99fd091ea11a5f143880a09f09c6d072fa67fb68
Bump to version v2.0.0
```
[ ] Yes
```
=> Major Release Version Bump to v2.0.0

lib/AuditLogs.php, lib/AuditTrail.php, lib/DirectorySync.php, lib/MFA.php, lib/Organizations.php, lib/Resource/BaseWorkOSResource.php, lib/Resource/Profile.php, lib/Resource/ProfileAndToken.php, lib/SSO.php
Hi @jonatascastro12, @sheldonvaughn, @hadihallak
Cf https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation
The `${foo}` syntax is deprecated in PHP 8.2 and should be replaced by `{$foo}`.
I also added `@property` annotation to `Profile` and `ProfileAndToken` classes in order to have autocompletion from PHPStorm or for static analysis tools like PHPStan. This way, both understand the syntax:
```
$profileAndToken->profile->email
```
No Need to update the doc.
=> Avoid PHP 8.2 deprecation

lib/Resource/Profile.php, tests/WorkOS/SSOTest.php
Add groups attribute to SSO user profile
```
[ ] Yes
```
=> Add groups attribute to SSO user profile

lib/Passwordless.php, lib/SSO.php
Hi, @sheldonvaughn 
When a connectionType is expected, the phpdoc is saying
```
@param null|\WorkOS\Resource\ConnectionType $provider
```
but this phpdoc is not correct:
- ConnectionType means the object connectionType, like `new ConnectionType()`
- a string is expected, like the constant `ConnectionType::GoogleOAuth`
You're kinda using the phpdoc like it was an enum but it's still a class. But some tool are understanding the syntax `ConnectionType::*` as "Any constant of the following class", this is the case of PHPStorm and PHPStan.
I fixed the phpdoc to `null|string` and added the special phpdoc with a `phpstan-` prefix.
I can remove the `phpstan` phpdoc if not wanted but, at least 
```
@param null|\WorkOS\Resource\ConnectionType
```
need to be fixed to
```
@param null|string
```
=> Fix ConnectionType usage in phpdoc

.github/CODEOWNERS
=> Fix team name in CODEOWNERS

lib/AuditLogs.php, lib/AuditTrail.php, lib/DirectorySync.php, lib/Exception/AuthenticationException.php, lib/Exception/AuthorizationException.php, lib/Exception/BadRequestException.php, lib/Exception/BaseRequestException.php, lib/Exception/ConfigurationException.php, lib/Exception/GenericException.php, lib/Exception/NotFoundException.php, lib/Exception/ServerException.php, lib/Exception/UnexpectedValueException.php, lib/Exception/WorkOSException.php, lib/MFA.php, lib/Organizations.php, lib/Passwordless.php, lib/Portal.php, lib/SSO.php, lib/WorkOS.php
Hi @sheldonvaughn,
The PHPdoc is missing a lot of `@throws` tag, most of the time it's because `::request` method is called and this can throw a lot of different WorkOS exceptions. I recently got the issue of not catching one of these exceptions, and this would have been caught thanks to phpdoc and PHPStorm/PHPStan.
Also, since the `::request` method can throw a lot of different exceptions:
```
@throws \WorkOS\Exception\GenericException if a client level exception is encountered
@throws \WorkOS\Exception\ServerException if a 5xx status code is returned
@throws \WorkOS\Exception\AuthenticationException if a 401 status code is returned
@throws \WorkOS\Exception\AuthorizationException if a 403 status code is returned
@throws \WorkOS\Exception\NotFoundException if a 404 status code is …
```
=> Add throws tag to every methods

composer.json
In the past we've had to add new Laravel versions to composer.json e.g. "illuminate/support" : "^5.0 || ^6.0 || ^7.0 || ^8.0 || ^9.0", however this dependency is unused in the PHP SDK.
```
[ ] Yes
```
=> Remove illuminate/support dependency to allow Laravel 10

lib/AuditLogs.php, tests/WorkOS/AuditLogsTest.php
- Adds `actorNames` and `actorIds` to `createExport`
- Deprecates `actors` in favor of `actorNames`
```
[x] Yes
```
=> Add `actorNames` and `actorIds` to `createExport`

tests/WorkOS/ClientTest.php
PR to unblock https://github.com/workos/workos-php/pull/149#pullrequestreview-1514851429
```
[ ] Yes
```
=> Fix syntax in Client Test breaking CI

lib/Resource/UserAndToken.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Adds the User Management Email Verification suite of functions:
https://workos.com/docs/reference/user-management/email-verification
Create an Email Verification Challenge
https://workos.com/docs/reference/user-management/email-verification/challenge
Complete Email Verification
https://workos.com/docs/reference/user-management/email-verification/verify
Resolves USRLD-745
```
[ ] Yes
```
=> Add `createEmailVerificationChallenge` and `completeEmailVerification` functions

lib/UserManagement.php
Removing the idempotency key from createUser() as it won't be used.
```
[ ] Yes
```
=> Drop idempotencyKey parameter from createUser()

lib/Resource/MagicAuthChallenge.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Adds the [Send Code](https://workos.com/docs/reference/user-management/magic-auth/send-code) function
```
[ ] Yes
```
=> Add `sendMagicAuthCode` function

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Updates the User Management Email Verification suite of functions to use the MagicAuthToken for validation.
```
[ ] Yes
```
=> Implement `MagicAuthToken` for Email Verification functions

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Adds User Management Password Reset suite of functions
https://workos.com/docs/reference/user-management/password-reset
Create Password Reset Challenge
https://workos.com/docs/reference/user-management/password-reset/challenge
Complete Password Reset Challenge
https://workos.com/docs/reference/user-management/password-reset/complete
```
[ ] Yes
```
=> Add `createPasswordResetChallenge` and `completePasswordReset` functions

lib/Resource/Session.php, lib/Resource/SessionAndUser.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Adds the User Management -> Session -> Authenticate User suite of functions:
Authenticate a User with Password: https://workos.com/docs/reference/user-management/session/authenticate-password
Authenticate an OAuth or SSO User: https://workos.com/docs/reference/user-management/session/authenticate-oauth-sso
Authenticate with Magic Auth: https://workos.com/docs/reference/user-management/session/authenticate-magic-auth
Also resolves USRLD-705, USRLD-710
```
[ ] Yes
```
=> Add `authenticateUserWith*`  functions

lib/Resource/User.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Renames email_verified_at to email_verified on User object. New type is boolean
Removes *_profile_id fields from User object
Removes user_type from User object
Removes type argument from listUsers
```
[ ] Yes
```
=> Updates `email_verified`, `*_profile_ids`, and `user_type` on `User` object

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Changes the `verifyEmail` function path from `users/{$userId}/verify_email` to `users/{$userId}/verify_email_code`
Changes the name of the `verifyEmail` function to `verifyEmailCode`
```
[ ] Yes
```
=> Update `verifyEmail` path and change name to `verifyEmailCode`

lib/Resource/UserResponse.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Changes `AuthenticateUserResponse` to `UserResponse`. 
Updates response of `verifyEmailCode` from `User` object to `UserResponse` with nested user object. 
Changes `completePasswordReset`  to `resetPassword` 
Updates response of `resetPassword` from `User` object to `UserResponse` with nested user object. 
Changes `createPasswordResetChallenge` to `sendPasswordResetEmail`
Also resolves USRLD-1090, USRLD-1097
```
[ ] Yes
```
=> Update nested user object in return

lib/Version.php
Bumping version to v3.4.0 to release .gitattributes file. 
```
[ ] Yes
```
=> Bump Version to 3.4.0

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Rename organization parameter filter
Use new API path
```
[ ] Yes
```
=> User Management - List Users: Rename organization parameter filter and use new path

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Update sendMagicAuthCode to use the right url and rename parameter
```
[ ] Yes
```
=> User Management - Update sendMagicAuthCode to use the right url and rename parameter

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
User Management - use new path for password reset flow
```
[ ] Yes
```
=> User Management - use new path for password reset flow

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
User Management - rename verifyEmailToken and rename path variables
```
[ ] Yes
```
=> User Management - rename verifyEmailToken and rename path variables

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
User Management - get Authorization URL
```
[ ] Yes
```
=> User Management - get Authorization URL

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
User Management - Validate provider value in getAuthorizationUrl
```
[ ] Yes
```
=> User Management - Validate provider value in getAuthorizationUrl

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Update return type of ResetPassword and sendPasswordResetEmail
```
[ ] Yes
```
=> Update return type of ResetPassword and sendPasswordResetEmail

lib/Exception/BaseRequestException.php, tests/WorkOS/ClientTest.php
Expose raw response in Exceptions to handle Authentication Errors
```
[ ] Yes
```
=> Expose raw response in Exceptions to handle Authentication Errors

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Add totp Issuer and User to enroll api
```
[ ] Yes
```
=> User Management - Add totp Issuer and User to enroll api

lib/Resource/User.php, tests/WorkOS/UserManagementTest.php
=> Add profile_picture_url attribute to the user object

lib/Resource/AuthenticationResponse.php, lib/Resource/Impersonator.php, tests/WorkOS/UserManagementTest.php
Adds support for the impersonator metadata in authentication responses.
```
[ ] Yes
```
=> Add `impersonator` attribute to `AuthenticationResponse`

lib/UserManagement.php, lib/Version.php, tests/WorkOS/UserManagementTest.php
This PR ensures that the User create process allows for the `password_hash` and `password_hash_type` fields, in addition to the existing `password` field, similar to the Update process.
```
[x] Yes
```
https://github.com/workos/workos/pull/26060
=> Add 'password_hash' and 'password_hash_type' to User creation

lib/Organizations.php, tests/WorkOS/OrganizationsTest.php
=> Add `domain_data` to Organization API and deprecate `domains`

lib/Resource/OrganizationMembership.php, tests/WorkOS/UserManagementTest.php
Adds new `status` attribute to organization membership.
```
[x] Yes
```
https://github.com/workos/workos/pull/25404
=> Add status to organization membership

lib/Resource/Invitation.php, lib/Resource/MagicAuth.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Adds events and API changes to support sending your own emails for invitations and Magic Auth.
- Adds `acceptInvitationUrl` to invitation object returned by API
- Adds new endpoints for the Magic Auth API: `getMagicAuth` and `createMagicAuth`
- Deprecates current `sendMagicAuthCode` method in favor of `createMagicAuth`
```
[x] Yes
```
https://github.com/workos/workos/pull/26691
=> Add API changes for invitations and Magic Auth

composer.json, lib/UserManagement.php, tests/WorkOS/AuditLogsTest.php, tests/WorkOS/ClientTest.php, tests/WorkOS/DirectorySyncTest.php, tests/WorkOS/MFATest.php, tests/WorkOS/SSOTest.php, tests/WorkOS/UserManagementTest.php
This PR: 
- Adds support for authentication with a refresh token
- Adds `getJwksUrl` helper method
- Upgrades phpunit to v10
- Fixes several language deprecations
- Fixes issues with method properties which should be optional https://github.com/workos/workos-php/issues/228
```
[ ] Yes
```
=> Auth with refresh token and fix some tests

lib/Resource/BaseWorkOSResource.php
This PR makes use of the `isset` function (see https://www.php.net/manual/en/function.isset.php) in order to check if a value exists within a Work OS resource.
This is the correct way to determine if a value exists within an array (currently, the native `ErrorException` error is raised when one tries to access a value that doesn't exist).
=> Properly check if a value exists within a BaseWorkOSResource

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Add organization membership deactivate and reactivate API methods.
```
[x] Yes
```
=> Add organization membership deactivate and reactivate API methods

lib/Resource/EmailVerification.php, lib/Resource/Invitation.php, lib/Resource/PasswordReset.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
- Add `inviterUserID` to invitation object
- Add `GET /user_management/email_verification/:id` endpoint
- Add `GET /user_management/password_reset/:id` and `POST /user_management/password_reset` endpoints
- Deprecate current send password reset endpoint
```
[x] Yes
```
https://github.com/workos/workos/pull/27414
=> Add methods and events for email verification and password reset

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Exposes find invitation by token API endpoint
```
[x] Yes
```
https://github.com/workos/workos/pull/27785
=> Add find invitation by token method

lib/Organizations.php, tests/WorkOS/OrganizationsTest.php
Deprecates the `$allowProfilesOutsideOrganization` parameter. Additionally, updates the create/update Organization methods to only serialize these options if an actual value has been passed.
Previously, `null` was always sent, which was fine for this particular endpoint, but is not a pattern that is guaranteed to have the same semantics everywhere.
```
[ ] Yes
```
=> Deprecate `$allowProfilesOutsideOrganization` parameter

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
An issue comes up when calling the getMagicAuth function: 
{
"message": "Cannot GET //user_management/magic_auth/magic_auth_XXXXXXXXXXXXXXXX",
"error": "Not Found"
}
The crux of the issue is that there's a double slash getting appended to the front of the route after the base URL. In looking at the base URL, it includes an ending slash '/' and the path for the API call also includes a leading slash so I believe this to be the cause of the discrepancy.
=> Remove leading slash from UM functions

lib/Version.php
Bumps version to 4.11.1 (bugfix, no new functionality)
```
[ ] Yes
```
=> Bump Version to 4.11.1

lib/Resource/ConnectionType.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Add `AppleOAuth` constants so SDK users can kick off login flows with Sign in with Apple.
The `GitHubOAuth` and 'MicrosoftOAuth` constants were partially missing, adding them too.
```
[ ] Yes
```
=> Add missing OAuth constants

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Adds support for the optional `organization_id` parameter for the `refresh_token` grant type.
```
[ ] Yes
```
=> Add `organizationId` parameter to `authenticateWithRefreshToken`

lib/Resource/WidgetScope.php, lib/Resource/WidgetTokenResponse.php, lib/Widgets.php, tests/WorkOS/WidgetsTest.php
Add widgets get token API support.
```
[ ] Yes
```
=> Add widgets get token API support

lib/Organizations.php, lib/Resource/Role.php, tests/WorkOS/OrganizationsTest.php
Add GET /organization/:orgId/roles support.
```
[ ] Yes
```
=> Add GET /organization/:orgId/roles support

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
Adds a new optional `return_to` option to `getLogoutUrl` to support the upcoming Logout URIs feature.
```
[ ] Yes
```
=> Add `return_to` option to `getLogoutUrl`

lib/AuditLogs.php, lib/Client.php, lib/DirectorySync.php, lib/Exception/BaseRequestException.php, lib/MFA.php, lib/Organizations.php, lib/Passwordless.php, lib/Portal.php, lib/RequestClient/CurlRequestClient.php, lib/RequestClient/RequestClientInterface.php, lib/Resource/AuthenticationFactorAndChallengeTotp.php, lib/Resource/BaseWorkOSResource.php, lib/Resource/Webhook.php, lib/SSO.php, lib/UserManagement.php, lib/Webhook.php, lib/Widgets.php, tests/WorkOS/AuditLogsTest.php, tests/WorkOS/ClientTest.php, tests/WorkOS/DirectorySyncTest.php, tests/WorkOS/MFATest.php, tests/WorkOS/OrganizationsTest.php, tests/WorkOS/PasswordlessTest.php, tests/WorkOS/PortalTest.php, tests/WorkOS/SSOTest.php, tests/WorkOS/UserManagementTest.php, tests/WorkOS/WebhookTest.php, tests/WorkOS/WidgetsTest.php
Hello,
Looking at the source, I found some PHPdoc that can be improved. The main fix is the return type of `constructFromResponse()` ([comment](https://github.com/workos/workos-php/pull/260#discussion_r1970498040)).
```
[ ] Yes
```
=> Improve PHPdoc types

.github/workflows/ci.yml, composer.json, lib/Resource/RoleResponse.php, lib/UserManagement.php, tests/WorkOS/ClientTest.php, tests/WorkOS/OrganizationsTest.php, tests/WorkOS/SSOTest.php, tests/WorkOS/UserManagementTest.php
This package is listed as requiring PHP >=7.3, but it seems to use some syntax introduced in PHP 8, as well as a version of PHPUnit that requires PHP 8. This pull request makes the minimal changes necessary to use this package in PHP 7.3.
https://github.com/workos/workos-php/blob/17bb8408033892cb3c0cc9e5e3fe833aeb32eec1/composer.json#L13
To test, I used the following `Dockerfile`:
```Dockerfile
FROM php:7.3.0
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions @composer
ADD . /workos-php
WORKDIR /workos-php
RUN composer install
ENTRYPOINT ["vendor/bin/phpunit"]
```
```sh
docker build . -t workos-php && docker run -it --rm workos-php
```
Strictly speaking, it wasn't necessary to update the tests and the PHPUnit version in …
=> Make workos-php compatible with PHP 7.3

lib/Organizations.php, lib/Resource/Organization.php, lib/Resource/User.php, lib/UserManagement.php, tests/WorkOS/OrganizationsTest.php, tests/WorkOS/UserManagementTest.php
And allow to be passed when creating or updating a user or organization.
```
[ ] Yes
```
=> Add metadata and external id

lib/Resource/DirectoryUser.php, tests/WorkOS/DirectorySyncTest.php
Add email standard attribute to DirectoryUser and mark deprecated standard attributes.
```
[ ] Yes
```
=> Add email standard attribute to DirectoryUser and mark deprecated standard attributes

lib/UserManagement.php
This PR adds support for creating a user with an external_id property, the option to get a user by their external_id, and the ability to update the external_id property for a user.
```
[ ] Yes
```
=> Add support for creating, getting and updating users with external_id property

lib/Resource/WebhookResponse.php, lib/Webhook.php, tests/WorkOS/Resource/WebhookResponseTest.php
This PR adds webhook response functionality to handle user registration and authentication actions. The implementation includes:
- Support for both "Allow" and "Deny" verdicts in webhook responses
- Support for "user_registration_action_response" and "authentication_action_response"
- Error message handling for denied verdicts
- JSON serialization support
- Validation for:
- Response types
- Verdict values
- Required error messages for deny verdicts
The changes improve webhook response handling by providing a structured way to respond to webhook events.
Example code in a Laravel app: 
```php
Route::post('work-os/user-registration-action', function (Request $request) {
$webhook = (new Webhook)->constructEvent(
$request->headers->get('WorkOS-Signature'),
$request->getContent(), …
```
=> Structured responses to webhook events

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
adds roleSlug param on createOrgMembership. Allows for updateOrgMembership to not require roleSlug.
```
[ ] Yes
```
=> add roleSlug for createOrgMembership and fix updateOrgMemberhship

lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
=> add email to UserManagement.updateUser

lib/Resource/Role.php, tests/WorkOS/OrganizationsTest.php
Currently it not possible to use WorkOS permissions in a PHP application as the Role resource is missing the `permissions` attribute. This PR simply addresses the issue. PHPDocs have also been added to the Role class.
```
[✔️] Yes
```
PHP example will need updating: https://workos.com/docs/reference/roles
Expected new PHP example based on JSON example.
```php
<?php
$role = [
"object" => "role",
"id" => "role_01EHQMYV6MBK39QC5PZXHY59C3",
"name" => "Member",
"slug" => "member",
"description" => "Access to basic resources",
"permissions" => ["posts:read", …
```
=> Add `permissions` attribute to Role

lib/Resource/AuthenticationResponse.php, lib/Resource/OAuthTokens.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
- adds support for the `oauth_tokens` object in the authenticate API response
- adds support for the new `provider_scopes` query parameter
```
[X] Yes
```
=> add support for custom scopes

.gitignore, lib/Resource/OrganizationMembership.php, lib/UserManagement.php, tests/WorkOS/UserManagementTest.php
- Add `roles` to organization membership resource responses (get, list, create, update, deactivate, reactivate)
- Add `roleSlugs` parameter to organization membership create and update options
```
[X] Yes
```
Will update the docs for these changes in **ENT-3687**
Tested locally against a team with multiple roles enabled. I tested OM get and update.
=> Adds multiple roles support to OrganizationMembership Create and Update

lib/Version.php
Version bump to 4.2.7.0
Includes:
- https://github.com/workos/workos-php/pull/291
- https://github.com/workos/workos-php/pull/293
- https://github.com/workos/workos-php/pull/302
```
[X] Yes
```
=> Version bump to 4.27.0
